### ISSUE TITLE
Create new sprite button is missing

### ISSUE THREAD

**Issue by pixelpicosean** [ndee85/coa_tools#1]
The addon is installed and enabled, and the "Cutout Anim" tab appears on the left side. But there's only a "3D View" button on "Cutout Animation Tools" panel. Is there any other requirement to be able to create the root sprite?

I am using Blender v2.76b.

**Comment by ndee85** [comment]
@pixelpicosean 
please try the download again. Hopefully it is fixed. Tried to modify the __init__.py in the operators directory.
Please report back if it works.

**Comment by pixelpicosean** [comment]
I download and installed again but still not lucky :disappointed: 
It does not work on OSX 10.11.3 but works on my PC (Windows 7).

**Comment by ndee85** [comment]
@pixelpicosean 
this is strange. I really don't understand where this issue comes from. Could you please tell me what the console writes.
Somebody else mentioned this issue already, but I have no mac to see what the problem is.

**Comment by pixelpicosean** [comment]
I run it from terminal and get the info below:

```sh
ndof: 3Dx driver not found
Read new prefs: /Users/sean/Library/Application Support/Blender/2.76/config/userpref.blend
found bundled python: /Applications/Blender/blender.app/Contents/MacOS/../Resources/2.76/python
Registered Cutout Animation Tools with 3 modules
```
There seems no issue at all. I'm trying to read the code and test.

**Comment by ndee85** [comment]
It seems the addon doesn't find the operator in the subdirectory. Right now I have no clue why. Maybe I can try it on my fathers mac tomorrow evening and find the problem.

**Comment by pixelpicosean** [comment]
I can now confirm that operators can not be found since warnings appear when I open the cutout anim tab. Can you tell me how the `operators` are registered by Blender? I am going to dirty my hands and try :smile:

**Comment by ndee85** [comment]
@pixelpicosean please try the github version again. Not the download link below.
I hope cd7a8e4 this commit fixes it.

**Comment by pixelpicosean** [comment]
@ndee85 It works now, thank you so much :smile:

**Comment by ndee85** [comment]
perfect. glad this issue has been solved. This was bothering me for quite some time now! :)
