### ISSUE TITLE
Sprite swaps look fine in preview, but don't render

### ISSUE THREAD

**Issue by GimmickyApps** [ndee85/coa_tools#20]
Hi,

I'm hoping you can help me with this one, I don't know what I might have done differently this time, but I reverted all my changes due to #19 and kept on normally with my existing sprites.  The problem I am suddenly encountering and cannot figure out why nor a workaround, is that when I hit Alt+A everything looks right (or if I move to any individual frame manually, also good) but when I render animation, the resulting frames are missing at least half of the sprite sheet swap-outs.  (Like if I selected a different face and made a new keyframe, it's different in the preview, but in the render it stays the same.)

An OpenGL render of the animation looks fine (except for the spare crap everywhere that's normal for an OpenGL render :) )

Any idea how to handle this?

Thanks,
Gimmicky

**Comment by GimmickyApps** [comment]
I think I've somewhat figured out the source of the problem: that I'm using two different cutout animations.  I couldn't figure out how I was supposed to do it, because the armature of one sprite/character seemed only to be stored in that character's cutout animations, while, the new part for me, sprite keyframes seem to get stored on both.  So as I went along editing both characters, because I wasn't switching first to the cutout animation of the character I was editing, now my changes are mixed among the two character's cutout animations so they both render wrong.

**Comment by ndee85** [comment]
This will be fixed with next Push. I have fixed this already.

**Comment by GimmickyApps** [comment]
Oh...is that also true for my situation?  That would be awesome :)

**Comment by GimmickyApps** [comment]
Like what I didn't understand was, when I made a new cutout anim on character2, and started animating, whatever the last selected cutout anim on character1 was, that was also being played back.  So I just made similar cutout anims on both characters and assumed I would have to have the corresponding cutout anims both as the last selected, but then either one would work.  Am I going about multi-char cutout anims wrong?

**Comment by ndee85** [comment]
Should be fixed with the latest github version.

**Comment by GimmickyApps** [comment]
I'm still experiencing this issue.  I pulled the changes, remade the zip file, went to Blender user preferences, said install from zip, clicked refresh, save changes, and tried a render.  Same result.

Was that the right way to upgrade, or should I uninstall the addon before reinstalling?

**Comment by GimmickyApps** [comment]
I just uninstalled and reinstalled, and tried again, and now it's actually worse: the preview no longer shows my sprite swaps either!  Just a moment ago they were showing, I had verified that just before trying a render.

**Comment by GimmickyApps** [comment]
It doesn't seem to make a difference if I reselect the animation in coa tools, the swaps don't reappear.  Help?

**Comment by GimmickyApps** [comment]
Oh, wait, I just restarted Blender, and now both the preview and the render seem to work!  Whew!  Thanks for the update!
